version: '3.8'

services:
  pgsql:
    container_name: product_flow_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: product_flow_db
    ports:
      - 5436:5432

  minio:
    container_name: product_flow_minio
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=qwe@1234
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /mnt/data:/data
    command: server /data --console-address ":9001"

  kafka:
    container_name: product_flow_kafka
    image: apache/kafka:3.9.1
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    container_name: product_flow_kafka_ui
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
    ports:
      - 8088:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: product-flow-cluster-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092